#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
defined('APP_BASE_PATH') or define('APP_BASE_PATH', __DIR__);
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(APP_BASE_PATH . '/app/Yii.php');

$config = require(APP_BASE_PATH . '/app/config/console.php');
if(file_exists(APP_BASE_PATH . '/app/config/local.php')){
    $config = yii\helpers\ArrayHelper::merge($config, require(APP_BASE_PATH . '/app/config/local.php'));
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
